### ISSUE TITLE
Adding docker support

### ISSUE THREAD

**Issue by niklasmh** [AscendNTNU/downward_target_tracker#2]
I am having some issues with compiling this project in docker. There may be some missing dependencies. Is it possible to add a working docker image/Dockerfile?

Error log:
![image](https://user-images.githubusercontent.com/8504538/32518096-df13e3f0-c408-11e7-916e-b6445cb5510c.png)

**Comment by lightbits** [comment]
Fixed (see latest commit on master). Did not use image_transport, so it is removed.
